kafka:
  topics:
    create-user:
      sender: ${KAFKA_CREATE_USER_SENDER:banking-microservices.create-user.money-service.success.v1}
      listener: ${KAFKA_CREATE_USER_LISTENER:banking-microservices.username-validation.user-service.progress.v1}
      error: ${KAFKA_CREATE_USER_ERROR:banking-microservices.create-user.money-service.error.v1}
    transaction:
      blockmoney:
        listener: ${KAFKA_TRANSACTION_BLOCKUSER_LISTENER:banking-microservices.transaction.transaction-service.created.v1}
        sender: ${KAFKA_TRANSACTION_BLOCKUSER_SENDER:banking-microservices.transaction.money-service.block-money.success.v1}
      transactionmoney:
        listener: ${KAFKA_TRANSACTION_TOPIC_LISTENER:banking-microservices.transaction.fraud-service.checked.v1}
        sender: ${KAFKA_TRANSACTION_TOPIC_SENDER:banking-microservices.transaction.transaction-service.success.v1}
      deposit:
        listener: ${KAFKA_TRANSACTION_TOPIC_DEPOSIT_LISTENER:banking-microservices.transaction.deposit.fraud-checked.v1}
        sender: ${KAFKA_TRANSACTION_TOPIC_DEPOSIT_SENDER:banking-microservices.transaction.deposit.money-service.success.v1}
      withdraw:
        listener: ${KAFKA_TRANSACTION_TOPIC_WITHDRAW_LISTENER:banking-microservices.transaction.withdraw.fraud-checked.v1}
        sender: ${KAFKA_TRANSACTION_TOPIC_WITHDRAW_SENDER:banking-microservices.transaction.withdraw.money-service.success.v1}
      error: ${KAFKA_TRANSACTION_TOPIC_ERROR:banking-microservices.transaction.transaction-service.error.v1}
    username-validation:
      sender: ${KAFKA_USERNAME_VALIDATION_SENDER:banking-microservices.username-validation.money-service.progress.v1}
      listener: ${KAFKA_USERNAME_VALIDATION_LISTENER:banking-microservices.username-validation.user-service.success.v1}

server:
  port: ${MONEY_SERVICE_PORT_NUMBER:8082}

spring:
  application:
    name: money-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: money-service-group
  cloud:
    kubernetes:
      discovery:
        enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/banking_money}
    username: ${SPRING_DATASOURCE_USERNAME:banking_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:local_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    root: INFO