server:
  port: ${GATEWAY_PORT_NUMBER:8095}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://auth-service:8084}
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: ${USER_SERVICE_URL:http://user-service:8081}
          predicates:
            - Path=/api/user/**

        - id: money-service
          uri: ${MONEY_SERVICE_URL:http://money-service:8082}
          predicates:
            - Path=/api/accounts/**

        - id: transaction-service
          uri: ${TRANSACTION_SERVICE_URL:http://transaction-service:8083}
          predicates:
            - Path=/api/transactions/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_TOKEN_ISSUER_URI:http://keycloak:8080/realms/banking}

  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/banking}
    username: ${SPRING_R2DBC_USERNAME:banking_admin}
    password: ${SPRING_R2DBC_PASSWORD:local_password}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      repositories:
        enabled: false

  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411}

management:
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always