server:
  port: ${GATEWAY_PORT_NUMBER:8082}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes: # rota demek.
        # Auth-Service icin rota
        - id: auth-service # tamamen benim belirledigim alan
          uri: ${AUTH_SERVICE_ROUTE_URI:http://auth-service:8084}
          predicates:
            - Path/api/auth/** # bu gatewaya gonderilen istegi auth serviceye gonderir ve direkt gonderir. /api/auth yerine gelen tum istekler oldugu gubu http://auth-service:8084 ye gider. eger api/auth varsa yine oldugu gibi gider

        # User Service Icin Routes
        - id: user-service
          uri: ${USER_SERVICE_ROUTE_URI:http://user-service:8084}
          predicates:
            - Path/api/users/**

        # Money Service
        - id: money-service
          uri: ${MONEY_SERVICE_ROUTE_URI:http://money-service:8082}
          predicates:
            - Path=/api/accounts/**

        # Transaction Service
        - id: transaction-service
          uri: ${TRANSACTION_SERVICE_ROUTE_URI:http://transaction-service:8083}
          predicates:
            - Path=/api/transactions/**

  security:
    oauth2:
      resourceserver: # kaynak sunucusu
        jwt: # jwt token kullaniyorum
          issuer-uri: ${JWT_TOKEN_ISSUER_URI:http://keycloak:8080/realms/banking-microservices} # tokeni ureten veren kaynak


  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      repositories:
        enabled: false
# Health check
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
