# Kubernet Icin Onemli Olanlar.
### 1
# spec (Specification) basligi ile type: LoadBalancer yazarsaniz uzaktan portunu yazarak erisilebilir. yazmazsaniz erisilemez.
# Yapmazsan Otomatik olarak type : ClusterIP olarak isaretlenir buda mikroservisler arasinda iletiism icindir disariya acik degildir.
# Gateway da LoadBalancer'dır ordan aldigi bilgileri ClusterIp olan veya olmayan mikroservislere yonlendrir.
### 2
## Dns ile haberlesme
# metadata:
#  name: keycloak
# namespace: banking-microservice
# Bu Seneryoda Dns ismi keycloack olucak ve diger mikroservisler keycloack:PORTNUMBER ile iletisim kurablecek buraya.



apiVersion: v1
kind: Namespace
metadata:
  name: banking-microservices # Namespace

---

#
#Postgres ConfigMap --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-database-init-configmap
  namespace: banking-microservices
data:
  # Postgres .sql ı gordugudne ve postgres'ı tanimladigimizda otomatik olarak calistirir GRANT ALL PRIVILEGES ON DATABASE full yetki verir dblere
  init-databases.sql: |
    CREATE DATABASE banking_auth;
    CREATE DATABASE banking_users;
    CREATE DATABASE banking_money;
    CREATE DATABASE banking_transactions;
    CREATE DATABASE banking_fraud;
    CREATE DATABASE banking;

    GRANT ALL PRIVILEGES ON DATABASE banking_auth TO banking_admin;
    GRANT ALL PRIVILEGES ON DATABASE banking_users TO banking_admin;
    GRANT ALL PRIVILEGES ON DATABASE banking_money TO banking_admin;
    GRANT ALL PRIVILEGES ON DATABASE banking_transactions TO banking_admin;
    GRANT ALL PRIVILEGES ON DATABASE banking_fraud TO banking_admin;
    GRANT ALL PRIVILEGES ON DATABASE banking TO banking_admin;
---
#
#Postgres Database Deployment Script --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#

apiVersion: apps/v1
# Deployment Nasil calistirilacaginin configini yapar.
kind: Deployment
metadata:
  name: postgres
  namespace: banking-microservices
# Spec: Specification yani information
spec:
  replicas: 1  # Kac Tane Pod calistirialcak
  selector:
    matchLabels:
      app: postgres # Tum podlarin uygulama ismi
  template:
    metadata:
      labels:
        app: postgres # Pod a yapistirilan etiket
    spec:
      containers:
        - name : postgres # " - " liste icin kullanilir
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: banking_admin
            - name: POSTGRES_PASSWORD
              value: banking_admin
            - name: POSTGRES_DB # Docker calistirildiktan sonra olustacak database. bu database init-databases.sql configini calistiracak ve ayri ayri databaseler olusturucak
              value: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data  # Container içindeki klasör PostgreSQL verilerini tutar
              name: postgres-data                   # Volume'un ismi (aşağıdaki volumes kısmıyla eşleşmeli)

            - mountPath: /docker-entrypoint-initdb.d  # Init script'lerin konulacağı klasör
              name: init-script                        # Volume'un ismi (ConfigMap'ten gelir)
      volumes:
        - name: postgres-data
          emptyDir: {} # Bos olmasini yani yeniden baslatildiginda silinmesini kaydolammasini saglar
        - name: init-script
          configMap:
            name: postgres-database-init-configmap # Init scriptini alacagi yer.

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: banking-microservices
spec:
  selector:
    app: postgres # postgres adina gelen tum istekleri bu alicak ve  app: postgres  adinda tanimlanan yere gondericek hepsini
  ports:
    - port: 5432 # veriyi alacagi port
      targetPort: 5432 # veriyi gonderecegi port

---

#
#REDIS CACHE SETTINGS --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: banking-microservices
spec:
  replicas: 1 # pod number
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort : 6379
---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: banking-microservices
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379

---
#
#ZIPKIN LOGGING SETTINGS --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: banking-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin

  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          ports:
            - containerPort: 9411
---

apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: banking-microservices
spec:
  selector:
    app: zipkin
  ports:
    - port: 9411
      targetPort: 9411

---

#
# Zookeper For Kafka ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper # Bunun altinda calisir deployment
  namespace: banking-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper # altinda calistigi uygulamalarin ismi deploymentin yonetecegi podlarin labeli. Bu podlari yonetecek
  template:
    metadata:
      labels:
        app: zookeeper # Podlarin etiketi. yukardakiyle ayni olmali
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.5.0
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper # Diger servisler bu isimle zookeeper:2181 seklinde ulasir. Kubernetes icinde DNS gibi calisir.
  namespace: banking-microservices
spec:
  selector:
    app: zookeeper # app: zookeeper etiketli podlara gelen tum istekleri bu service karsilar ve yonlendirir
  ports:
    - port: 2181 # Zookeeper'in dinledigi standart port. Kafka metadata bilgilerini buradan alir. Topic, partition bilgileri burada tutulur.
      targetPort: 2181 # Container icindeki porta yonlendir. port ve targetPort genelde ayni olur ama farkli da olabilir.

---

#
# KAFKA DEPLOYMENT --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: banking-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka  # "app=kafka" etiketli pod'ları yönet
  template:
    metadata:
      labels:
        app: kafka  # Oluşturulacak pod'lara "app=kafka" etiketi yapıştır
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: banking-microservices
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092

---

#
# KEYCLOAK ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: banking-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: alper123
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: alper123A
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT
              value: "false"

---

apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: banking-microservices
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

---

